import Head from "next/head";
import Image from "next/image";

import { useAuth } from "../firebase";
import Header from "../components/Header";

export default function Home() {
  const currentUser = useAuth();

  return (
    <div className="flex-column">
      <Head>
        <title>pyNotes</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />
      <main>
        <div></div>
      </main>

      <footer className="fixed bottom-0 w-full border-t p-4 text-center ">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
